import log from 'customLog'

process.on('unhandledRejection', (err) => {
  log.error('ğŸ›‘ RejeiÃ§Ã£o nÃ£o tratada', err)
})

process.on('uncaughtException', (err) => {
  log.error('ğŸ›‘ Erro nÃ£o tratado', err)
})
